[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q --strict-markers
markers =
    anyio: تست‌های ناهمگام (اجرا با پلاگین anyio)
filterwarnings =
    ignore::DeprecationWarning
